gorm:
  clusters:
    - tables:
        - users
      masters:
        - host: localhost
          port: 5442
          user: postgres
          password: postgres
          database: users
          sslmode: disable
          timezone: UTC
          connect_timeout: 2s
      replicas:
        - host: localhost
          port: 5443
          user: postgres
          password: postgres
          database: users
          sslmode: disable
          timezone: UTC
          connect_timeout: 2s
      log_resolver_trace: true

    - tables:
        - games
      masters:
        - host: localhost
          port: 5452
          user: postgres
          password: postgres
          database: games
          sslmode: disable
          timezone: UTC
          connect_timeout: 2s
      replicas:
        - host: localhost
          port: 5453
          user: postgres
          password: postgres
          database: games
          sslmode: disable
          timezone: UTC
          connect_timeout: 2s
      log_resolver_trace: true
